set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TOOLCHAIN_ROOT /opt/linux/x86-arm/aarch64-v01c01-linux-gnu-gcc)
set(TOOLCHAIN_BIN ${TOOLCHAIN_ROOT}/bin)

set(CMAKE_C_COMPILER ${TOOLCHAIN_BIN}/aarch64-v01c01-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BIN}/aarch64-v01c01-linux-gnu-g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_BIN}/aarch64-v01c01-linux-gnu-gcc)

set(CMAKE_AR ${TOOLCHAIN_BIN}/aarch64-v01c01-linux-gnu-ar)
set(CMAKE_RANLIB ${TOOLCHAIN_BIN}/aarch64-v01c01-linux-gnu-ranlib)
set(CMAKE_STRIP ${TOOLCHAIN_BIN}/aarch64-v01c01-linux-gnu-strip)

set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CROSSCOMPILING TRUE)