include_guard(GLOBAL)

function(_lvgl_prune_conf_value CONF_PATH MACRO OUT_VAR)
    set(_value "")

    if(EXISTS "${CONF_PATH}")
        file(STRINGS "${CONF_PATH}" _matches
                REGEX "^[ \t]*#[ \t]*define[ \t]+${MACRO}([ \t]+|$)")

        foreach(_line IN LISTS _matches)
            string(REGEX REPLACE "/\\*.*\\*/" "" _clean "${_line}")
            string(REGEX REPLACE "//.*$" "" _clean "${_clean}")
            string(REGEX REPLACE "^[ \t]*#[ \t]*define[ \t]+${MACRO}[ \t]*" "" _value "${_clean}")
            string(STRIP "${_value}" _value)
        endforeach()
    endif()

    set(${OUT_VAR} "${_value}" PARENT_SCOPE)
endfunction()

function(_lvgl_prune_truthy VALUE OUT_VAR)
    string(TOUPPER "${VALUE}" _upper_value)

    if(_upper_value MATCHES "^(1|ON|YES|TRUE|Y)$")
        set(${OUT_VAR} TRUE PARENT_SCOPE)
    else()
        set(${OUT_VAR} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_lvgl_prune_conf_enabled CONF_PATH MACRO OUT_VAR)
    set(_config_name "CONFIG_${MACRO}")

    if(DEFINED ${_config_name})
        if(${_config_name})
            set(${OUT_VAR} TRUE PARENT_SCOPE)
        else()
            set(${OUT_VAR} FALSE PARENT_SCOPE)
        endif()
        return()
    endif()

    _lvgl_prune_conf_value("${CONF_PATH}" "${MACRO}" _value)
    _lvgl_prune_truthy("${_value}" _enabled)
    set(${OUT_VAR} ${_enabled} PARENT_SCOPE)
endfunction()

function(_lvgl_prune_remove SOURCE_VAR)
    foreach(_pattern IN LISTS ARGN)
        list(FILTER ${SOURCE_VAR} EXCLUDE REGEX "${_pattern}")
    endforeach()

    set(${SOURCE_VAR} "${${SOURCE_VAR}}" PARENT_SCOPE)
endfunction()

function(_lvgl_prune_if_disabled SOURCE_VAR CONF_PATH MACRO)
    _lvgl_prune_conf_enabled("${CONF_PATH}" "${MACRO}" _enabled)

    if(NOT _enabled)
        _lvgl_prune_remove(${SOURCE_VAR} ${ARGN})
    endif()

    set(${SOURCE_VAR} "${${SOURCE_VAR}}" PARENT_SCOPE)
endfunction()

function(_lvgl_prune_unless_any_enabled SOURCE_VAR CONF_PATH MACROS)
    set(_any_enabled FALSE)

    foreach(_macro IN LISTS MACROS)
        _lvgl_prune_conf_enabled("${CONF_PATH}" "${_macro}" _enabled)
        if(_enabled)
            set(_any_enabled TRUE)
        endif()
    endforeach()

    if(NOT _any_enabled)
        _lvgl_prune_remove(${SOURCE_VAR} ${ARGN})
    endif()

    set(${SOURCE_VAR} "${${SOURCE_VAR}}" PARENT_SCOPE)
endfunction()

function(_lvgl_prune_if_value_not SOURCE_VAR CONF_PATH MACRO EXPECTED_VALUE)
    _lvgl_prune_conf_value("${CONF_PATH}" "${MACRO}" _value)

    if(NOT "${_value}" STREQUAL "${EXPECTED_VALUE}")
        _lvgl_prune_remove(${SOURCE_VAR} ${ARGN})
    endif()

    set(${SOURCE_VAR} "${${SOURCE_VAR}}" PARENT_SCOPE)
endfunction()

function(lvgl_sync_build_options_from_conf CONF_PATH)
    foreach(_macro IN ITEMS
            LV_BUILD_DEMOS
            LV_BUILD_EXAMPLES
            LV_USE_PRIVATE_API
            LV_USE_THORVG_INTERNAL)
        _lvgl_prune_conf_value("${CONF_PATH}" "${_macro}" _value)

        if(NOT "${_value}" STREQUAL "")
            _lvgl_prune_truthy("${_value}" _enabled)

            if(_enabled)
                set(_cmake_value ON)
            else()
                set(_cmake_value OFF)
            endif()

            set(CONFIG_${_macro} ${_cmake_value} CACHE BOOL "Mirrored from ${CONF_PATH}" FORCE)
        endif()
    endforeach()
endfunction()

function(lvgl_prune_unused_sources TARGET_NAME CONF_PATH)
    if(NOT TARGET ${TARGET_NAME})
        message(FATAL_ERROR "Target '${TARGET_NAME}' does not exist")
    endif()

    get_target_property(_sources ${TARGET_NAME} SOURCES)
    if(NOT _sources OR _sources STREQUAL "_sources-NOTFOUND")
        message(WARNING "Target '${TARGET_NAME}' has no sources to prune")
        return()
    endif()

    list(LENGTH _sources _before_count)
    set(_pruned ${_sources})

    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_MONKEY "/src/debugging/monkey/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SYSMON "/src/debugging/sysmon/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_TEST "/src/debugging/test/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_VG_LITE_THORVG "/src/debugging/vg_lite_tvg/")

    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_DRAW_DMA2D "/src/draw/dma2d/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_PPA "/src/draw/espressif/ppa/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_DRAW_EVE "/src/draw/eve/" "/src/drivers/draw/eve/" "/src/libs/FT800-FT813/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_DRAW_NANOVG "/src/draw/nanovg/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_NEMA_GFX "/src/draw/nema_gfx/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_G2D "/src/draw/nxp/g2d/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_PXP "/src/draw/nxp/pxp/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_DRAW_OPENGLES "/src/draw/opengles/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_DRAW_DAVE2D "/src/draw/renesas/dave2d/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_DRAW_SDL "/src/draw/sdl/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SNAPSHOT "/src/draw/snapshot/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_DRAW_SW "/src/draw/sw/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_DRAW_VG_LITE "/src/draw/vg_lite/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_VG_LITE_DRIVER "/src/libs/vg_lite_driver/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_VECTOR_GRAPHIC "/src/draw/lv_draw_vector\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_3DTEXTURE "/src/draw/lv_draw_3d\\.c$" "/src/widgets/3dtexture/")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_DRAW_SW_ASM LV_DRAW_SW_ASM_HELIUM
            "/src/draw/convert/helium/" "/src/draw/sw/blend/helium/")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_DRAW_SW_ASM LV_DRAW_SW_ASM_NEON
            "/src/draw/convert/neon/" "/src/draw/sw/blend/neon/")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_DRAW_SW_ASM LV_DRAW_SW_ASM_RISCV_V
            "/src/draw/sw/blend/riscv_v/")

    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LINUX_DRM "/src/drivers/display/drm/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LINUX_FBDEV "/src/drivers/display/fb/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FT81X "/src/drivers/display/ft81x/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ILI9341 "/src/drivers/display/ili9341/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LOVYAN_GFX "/src/drivers/display/lovyan_gfx/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_NV3007 "/src/drivers/display/nv3007/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_NXP_ELCDIF "/src/drivers/display/nxp_elcdif/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_RENESAS_GLCDC "/src/drivers/display/renesas_glcdc/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ST7735 "/src/drivers/display/st7735/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ST7789 "/src/drivers/display/st7789/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ST7796 "/src/drivers/display/st7796/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ST_LTDC "/src/drivers/display/st_ltdc/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_TFT_ESPI "/src/drivers/display/tft_espi/")
    _lvgl_prune_unless_any_enabled(_pruned "${CONF_PATH}" "LV_USE_GENERIC_MIPI;LV_USE_ST7735;LV_USE_ST7789;LV_USE_ST7796;LV_USE_ILI9341;LV_USE_NV3007"
            "/src/drivers/display/lcd/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_EVDEV "/src/drivers/evdev/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LIBINPUT "/src/drivers/libinput/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_NUTTX "/src/drivers/nuttx/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_OPENGLES "/src/drivers/opengles/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_QNX "/src/drivers/qnx/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SDL "/src/drivers/sdl/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_UEFI "/src/drivers/uefi/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_WAYLAND "/src/drivers/wayland/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_WINDOWS "/src/drivers/windows/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_X11 "/src/drivers/x11/")

    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_8 "/src/font/lv_font_montserrat_8\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_10 "/src/font/lv_font_montserrat_10\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_12 "/src/font/lv_font_montserrat_12\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_14 "/src/font/lv_font_montserrat_14\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_16 "/src/font/lv_font_montserrat_16\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_18 "/src/font/lv_font_montserrat_18\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_20 "/src/font/lv_font_montserrat_20\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_22 "/src/font/lv_font_montserrat_22\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_24 "/src/font/lv_font_montserrat_24\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_26 "/src/font/lv_font_montserrat_26\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_28 "/src/font/lv_font_montserrat_28\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_28_COMPRESSED "/src/font/lv_font_montserrat_28_compressed\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_30 "/src/font/lv_font_montserrat_30\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_32 "/src/font/lv_font_montserrat_32\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_34 "/src/font/lv_font_montserrat_34\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_36 "/src/font/lv_font_montserrat_36\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_38 "/src/font/lv_font_montserrat_38\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_40 "/src/font/lv_font_montserrat_40\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_42 "/src/font/lv_font_montserrat_42\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_44 "/src/font/lv_font_montserrat_44\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_46 "/src/font/lv_font_montserrat_46\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_MONTSERRAT_48 "/src/font/lv_font_montserrat_48\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_DEJAVU_16_PERSIAN_HEBREW "/src/font/lv_font_dejavu_16_persian_hebrew\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_SOURCE_HAN_SANS_SC_14_CJK "/src/font/lv_font_source_han_sans_sc_14_cjk\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_SOURCE_HAN_SANS_SC_16_CJK "/src/font/lv_font_source_han_sans_sc_16_cjk\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_UNSCII_8 "/src/font/lv_font_unscii_8\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FONT_UNSCII_16 "/src/font/lv_font_unscii_16\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FONT_MANAGER "/src/font/font_manager/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_IMGFONT "/src/font/imgfont/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ARABIC_PERSIAN_CHARS "/src/misc/lv_text_ap\\.c$")

    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_GRIDNAV "/src/indev/lv_gridnav\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_GESTURE_RECOGNITION "/src/indev/lv_indev_gesture\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FLEX "/src/layouts/flex/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_GRID "/src/layouts/grid/")

    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_OS LV_OS_NONE "/src/osal/lv_os_none\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_OS LV_OS_PTHREAD "/src/osal/lv_pthread\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_OS LV_OS_FREERTOS "/src/osal/lv_freertos\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_OS LV_OS_CMSIS_RTOS2 "/src/osal/lv_cmsis_rtos2\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_OS LV_OS_RTTHREAD "/src/osal/lv_rtthread\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_OS LV_OS_WINDOWS "/src/osal/lv_windows\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_OS LV_OS_MQX "/src/osal/lv_mqx\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_OS LV_OS_SDL2 "/src/osal/lv_sdl2\\.c$")

    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_MALLOC LV_STDLIB_BUILTIN
            "/src/stdlib/builtin/lv_mem_core_builtin\\.c$" "/src/stdlib/builtin/lv_tlsf\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_STRING LV_STDLIB_BUILTIN
            "/src/stdlib/builtin/lv_string_builtin\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_SPRINTF LV_STDLIB_BUILTIN
            "/src/stdlib/builtin/lv_sprintf_builtin\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
            "/src/stdlib/clib/lv_mem_core_clib\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_STRING LV_STDLIB_CLIB
            "/src/stdlib/clib/lv_string_clib\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB
            "/src/stdlib/clib/lv_sprintf_clib\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_MALLOC LV_STDLIB_MICROPYTHON
            "/src/stdlib/micropython/")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_MALLOC LV_STDLIB_RTTHREAD
            "/src/stdlib/rtthread/lv_mem_core_rtthread\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_STRING LV_STDLIB_RTTHREAD
            "/src/stdlib/rtthread/lv_string_rtthread\\.c$")
    _lvgl_prune_if_value_not(_pruned "${CONF_PATH}" LV_USE_STDLIB_SPRINTF LV_STDLIB_RTTHREAD
            "/src/stdlib/rtthread/lv_sprintf_rtthread\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_UEFI "/src/stdlib/uefi/")

    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_BARCODE "/src/libs/barcode/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_BMP "/src/libs/bmp/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FFMPEG "/src/libs/ffmpeg/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FREETYPE "/src/libs/freetype/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_FREETYPE_USE_LVGL_PORT "/src/libs/freetype/lv_ftsystem\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_FATFS "/src/libs/fsdrv/lv_fs_fatfs\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_FROGFS "/src/libs/fsdrv/lv_fs_frogfs\\.c$" "/src/libs/frogfs/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_LITTLEFS "/src/libs/fsdrv/lv_fs_littlefs\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_MEMFS "/src/libs/fsdrv/lv_fs_memfs\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_POSIX "/src/libs/fsdrv/lv_fs_posix\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_STDIO "/src/libs/fsdrv/lv_fs_stdio\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_UEFI "/src/libs/fsdrv/lv_fs_uefi\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_WIN32 "/src/libs/fsdrv/lv_fs_win32\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_ARDUINO_ESP_LITTLEFS "/src/libs/fsdrv/lv_fs_arduino_esp_littlefs\\.cpp$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FS_ARDUINO_SD "/src/libs/fsdrv/lv_fs_arduino_sd\\.cpp$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_GIF "/src/libs/gif/" "/src/widgets/gif/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_GLTF "/src/libs/gltf/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_GSTREAMER "/src/libs/gstreamer/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LIBJPEG_TURBO "/src/libs/libjpeg_turbo/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LIBPNG "/src/libs/libpng/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LIBWEBP "/src/libs/libwebp/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LODEPNG "/src/libs/lodepng/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LZ4_INTERNAL "/src/libs/lz4/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_NANOVG "/src/libs/nanovg/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_QRCODE "/src/libs/qrcode/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_RLE "/src/libs/rle/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_RLOTTIE "/src/libs/rlottie/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SVG "/src/libs/svg/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_THORVG_INTERNAL "/src/libs/thorvg/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_TINY_TTF "/src/libs/tiny_ttf/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_TJPGD "/src/libs/tjpgd/")

    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_OBJ_ID "/src/core/lv_obj_id_builtin\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_OBJ_PROPERTY "/src/core/lv_obj_property\\.c$" "/src/widgets/property/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_OBSERVER "/src/core/lv_observer\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FILE_EXPLORER "/src/others/file_explorer/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_FRAGMENT "/src/others/fragment/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_TRANSLATION "/src/others/translation/")

    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ANIMIMG "/src/widgets/animimage/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ARC "/src/widgets/arc/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ARCLABEL "/src/widgets/arclabel/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_BAR "/src/widgets/bar/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_BUTTON "/src/widgets/button/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_BUTTONMATRIX "/src/widgets/buttonmatrix/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_CALENDAR "/src/widgets/calendar/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_CALENDAR_CHINESE "/src/widgets/calendar/lv_calendar_chinese\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_CALENDAR_HEADER_ARROW "/src/widgets/calendar/lv_calendar_header_arrow\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_CALENDAR_HEADER_DROPDOWN "/src/widgets/calendar/lv_calendar_header_dropdown\\.c$")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_CANVAS "/src/widgets/canvas/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_CHART "/src/widgets/chart/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_CHECKBOX "/src/widgets/checkbox/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_DROPDOWN "/src/widgets/dropdown/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_IMAGE "/src/widgets/image/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_IMAGEBUTTON "/src/widgets/imagebutton/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_IME_PINYIN "/src/widgets/ime/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_KEYBOARD "/src/widgets/keyboard/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LABEL "/src/widgets/label/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LED "/src/widgets/led/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LINE "/src/widgets/line/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LIST "/src/widgets/list/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_LOTTIE "/src/widgets/lottie/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_MENU "/src/widgets/menu/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_MSGBOX "/src/widgets/msgbox/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_ROLLER "/src/widgets/roller/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SCALE "/src/widgets/scale/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SLIDER "/src/widgets/slider/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SPAN "/src/widgets/span/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SPINBOX "/src/widgets/spinbox/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SPINNER "/src/widgets/spinner/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_SWITCH "/src/widgets/switch/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_TABLE "/src/widgets/table/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_TABVIEW "/src/widgets/tabview/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_TEXTAREA "/src/widgets/textarea/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_TILEVIEW "/src/widgets/tileview/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_WIN "/src/widgets/win/")
    _lvgl_prune_remove(_pruned "/src/font/lv_font_montserrat_14_aligned\\.c$" "/src/widgets/objx_templ/")

    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_THEME_DEFAULT "/src/themes/default/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_THEME_SIMPLE "/src/themes/simple/")
    _lvgl_prune_if_disabled(_pruned "${CONF_PATH}" LV_USE_THEME_MONO "/src/themes/mono/")

    list(LENGTH _pruned _after_count)
    math(EXPR _removed_count "${_before_count} - ${_after_count}")

    set_property(TARGET ${TARGET_NAME} PROPERTY SOURCES ${_pruned})
    message(STATUS "LVGL: pruned ${_removed_count} disabled source files from target '${TARGET_NAME}' (${_after_count}/${_before_count} kept)")
endfunction()
